name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          msbuild WeaponLimitsAdjuster.sln -m -p:Configuration=${{ matrix.config }} -p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: gtav-WeaponLimitsAdjuster-${{ matrix.config }}
          path: x64/${{ matrix.config }}